### ISSUE TITLE
Filter out long lines

### ISSUE THREAD

**Issue by mrthebob** [jreybert/cgvg#1]
Boy, it would sure be nice if cgvg could filter out really long lines that eat up real estate.  (Or truncate them...).  I get a lot of compressed files in the output, making it hard to scroll.

(BTW, I use both the Linux and the Mac versions)

**Comment by jreybert** [comment]
OMG, I should have make it clear that this repo is just a sightly hacked version of cgvg... You may try to find the official repository (if any) or contact the original author (Joshua Uziel <uzi@uzix.org>).

I don't use cgvg anymore, and I am quite reluctant to browse perl code :(

Sorry dude, I think I'll pass this time.
